name: Build and Deploy Python App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies required by pyodbc
      run: sudo apt-get update && sudo apt-get install -y unixodbc-dev g++    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
