name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4  

    - name: Set up Python
      uses: actions/setup-python@v4  

      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y unixodbc-dev g++


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4  
      with:
        name: python-app
        path: .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: falaskapp-wb
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
